from __future__ import annotations

INTRA_BP_PARAM_NAME = "X"
INTER_BP_PARAM_NAME = "Y"
B2P_WATSON_PARAM_NAME = "W"
B2P_CRICK_PARAM_NAME = "C"


INTRA_BP_JUNC_NAME = "x"
INTER_BP_JUNC_NAME = "y"
B2P_WATSON_JUNC_NAME = "w"
B2P_CRICK_JUNC_NAME = "c"

C2BP_JUNC_NAME = "l"
BP2W_JUNC_NAME = "r"

WATSON_BASE_NAME = "bw"
CRICK_BASE_NAME = "bc"
WATSON_PHOSPHATE_NAME = "pw"
CRICK_PHOSPHATE_NAME = "pc"

PARAM_BASENAMES = [
    B2P_WATSON_PARAM_NAME,
    INTRA_BP_PARAM_NAME,
    B2P_CRICK_PARAM_NAME,
    INTER_BP_PARAM_NAME,
]

BP_NAME = "bp"
